# Default values for home chart
replicaCount: 1

image:
  repository: nginx
  tag: "alpine"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Home page specific configuration
home:
  title: "Agent Docs"
  subtitle: "Documentation and API Reference"
  description: "Welcome to the Agent Documentation Service"
  
# Content configuration
content:
  # Static HTML content for the home page
  html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{{ .Values.home.title }}</title>
        <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
            .container { max-width: 800px; margin: 0 auto; background: white; padding: 40px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            h1 { color: #333; margin-bottom: 10px; }
            .subtitle { color: #666; font-size: 1.2em; margin-bottom: 20px; }
            .description { color: #555; line-height: 1.6; margin-bottom: 30px; }
            .links { display: flex; gap: 20px; flex-wrap: wrap; }
            .link { padding: 10px 20px; background: #007bff; color: white; text-decoration: none; border-radius: 4px; }
            .link:hover { background: #0056b3; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>{{ .Values.home.title }}</h1>
            <div class="subtitle">{{ .Values.home.subtitle }}</div>
            <div class="description">{{ .Values.home.description }}</div>
            <div class="links">
                <a href="/docs" class="link">Documentation</a>
                <a href="/api" class="link">API Reference</a>
                <a href="/health" class="link">Health Check</a>
            </div>
        </div>
    </body>
    </html>
