apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-node.fullname" . }}-headless
  labels:
    {{- include "generic-node.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end }}
  selector:
    {{- include "generic-node.selectorLabels" . | nindent 4 }}
