{{- range .Values.statefulsets }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .name | quote }}
  labels:
    {{- include "generic-node.labels" $ | nindent 4 }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
spec:
  podManagementPolicy: {{ .podManagementPolicy | default $.Values.global.podManagementPolicy }}
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "generic-node.selectorLabels" $ | nindent 6 }}
  serviceName: {{ include "generic-node.fullname" $ }}-headless
  updateStrategy:
  {{- .updateStrategy | default $.Values.global.updateStrategy | toYaml | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "generic-node.selectorLabels" $ | nindent 8 }}
        {{- with .podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .podAnnotations }}
      annotations:
        {{- with .podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "generic-node.serviceAccountName" $ }}
    {{- if .priorityClassName }}
      priorityClassName: {{ .priorityClassName }}
    {{- end }}
      securityContext:
        {{- .securityContext | default $.Values.global.podSecurityContext | toYaml | nindent 8 }}
      {{- if .initContainers }}
      initContainers:
        {{- tpl (toYaml .initContainers | nindent 8) $ }}
      {{- end }}
      {{- with .imagePullSecrets | default $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- $defaultMounthPath := .persistence.defaultMountPath | default "/data" }}
        {{- range .containers }}
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy | default $.Values.global.imagePullPolicy }}
          {{- with .command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{ .securityContext | default $.Values.global.containerSecurityContext | toYaml | nindent 12 }}
          volumeMounts:
            {{- if .extraVolumeMounts }}
              {{ toYaml .extraVolumeMounts | nindent 12}}
            {{- end }}
            - name: storage
              mountPath: {{ $defaultMounthPath | quote }}
          ports:
            {{- if .extraContainerPorts }}
              {{ toYaml .extraContainerPorts | nindent 12}}
            {{- end }}
            {{- range $.Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- if .startupProbe }}
          startupProbe:
            {{- toYaml .startupProbe | nindent 12 }}
          {{- end }}
          {{- if .livenessProbe }}
          livenessProbe:
            {{- toYaml .livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .readinessProbe }}
          readinessProbe:
            {{- toYaml .readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- end }}
          {{- if .env }}
          env:
            {{- toYaml .env | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .affinity }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      {{- end }}
      {{- if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      {{- end }}
      {{- if .topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{- if .terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .terminationGracePeriodSeconds }}
      {{- end }}
      volumes:
      {{- if .extraVolumes }}
        {{ toYaml .extraVolumes | nindent 8}}
      {{- end }}
  {{- if not .persistence.enabled }}
        - name: storage
          emptyDir: {}
  {{- else if .persistence.existingClaim }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .persistence.existingClaim }}
  {{- else }}
  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
        {{- toYaml .persistence.annotations | nindent 8 }}
    spec:
      accessModes:
        {{- toYaml .persistence.accessModes | nindent 8 }}
      resources:
        requests:
          storage: {{ .persistence.size | quote }}
      storageClassName: {{ .persistence.storageClassName }}
      {{- if .persistence.selector }}
      selector:
        {{- toYaml .persistence.selector | nindent 8 }}
      {{- end }}
  {{- end }}
{{- end }}
