{{- if .Values.vault.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: {{ include "generic-node.fullname" . }}
spec:
  appName: {{ .Values.vault.app }}
  {{- if .Values.vault.rolloutRestartTargets }}
  rolloutRestartTargets:
    {{- toYaml .Values.vault.rolloutRestartTargets | nindent 4 }}
  {{- end }}
  destination:
    create: true
    labels:
      hvs: "true"
    name: {{ include "generic-node.fullname" . }}
  refreshAfter: {{ .Values.vault.refreshAfter }}
{{- end }}
