apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home.fullname" . }}-content
  labels:
    {{- include "home.labels" . | nindent 4 }}
data:
  index.html: |
{{ .Values.content.html | nindent 4 }}
