apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agent-docs-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "agent-docs-server.name" . }}
    helm.sh/chart: {{ include "agent-docs-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "agent-docs-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "agent-docs-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
{{- with .Values.podAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ include "agent-docs-server.serviceAccountName" . }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
      {{- end }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
{{ toYaml .Values.securityContext | indent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            {{- if .Values.secret.existingSecret }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.existingSecret }}
                  key: {{ .Values.secret.keys.DATABASE_URL }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.existingSecret }}
                  key: {{ .Values.secret.keys.OPENAI_API_KEY }}
            {{- if .Values.secret.keys.ANTHROPIC_API_KEY }}
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.existingSecret }}
                  key: {{ .Values.secret.keys.ANTHROPIC_API_KEY }}
            {{- end }}
            {{- else }}
            - name: DATABASE_URL
              value: {{ required "DATABASE_URL must be set" .Values.env.DATABASE_URL | quote }}
            - name: OPENAI_API_KEY
              value: {{ .Values.env.OPENAI_API_KEY | quote }}
            {{- end }}
            - name: RUST_LOG
              value: {{ .Values.env.RUST_LOG | quote }}
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: MCP_HOST
              value: {{ .Values.env.MCP_HOST | quote }}
            - name: INGEST_WORK_DIR
              value: {{ ternary .Values.persistence.mountPath .Values.env.INGEST_WORK_DIR .Values.persistence.enabled | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          volumeMounts:
            - name: tools-config
              mountPath: /app/tools.json
              subPath: tools.json
              readOnly: true
            - name: workdir
              mountPath: {{ if .Values.persistence.enabled }}{{ .Values.persistence.mountPath }}{{ else }}/tmp{{ end }}
              readOnly: false
      volumes:
        - name: tools-config
          configMap:
            name: {{ include "agent-docs-server.fullname" . }}-config
            items:
              - key: tools.json
                path: tools.json
        - name: workdir
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{ else }}{{ include "agent-docs-server.fullname" . }}-workdir{{ end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
