{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "agent-docs-server.fullname" . }}-migrations
  labels:
    app.kubernetes.io/name: {{ include "agent-docs-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{- with .Values.migrations.annotations }}
{{ toYaml . | indent 2 }}
{{- end }}
spec:
  backoffLimit: {{ .Values.migrations.backoffLimit }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "agent-docs-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "agent-docs-server.serviceAccountName" . }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/http_server"]
          args: ["--migrate-only"]
          env:
            {{- if .Values.secret.existingSecret }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.existingSecret }}
                  key: {{ .Values.secret.keys.DATABASE_URL }}
            {{- else }}
            - name: DATABASE_URL
              value: {{ required "DATABASE_URL must be set" .Values.env.DATABASE_URL | quote }}
            {{- end }}
            - name: RUST_LOG
              value: {{ .Values.env.RUST_LOG | quote }}
          {{- range .Values.migrations.extraEnv }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
          {{- end }}
          resources:
{{ toYaml .Values.migrations.resources | indent 12 }}
      activeDeadlineSeconds: {{ .Values.migrations.activeDeadlineSeconds }}
{{- end }}


