apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jupiter-chart.fullname" . }}
  labels:
    {{- include "jupiter-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "jupiter-chart.selectorLabels" . | nindent 6 }}
  {{- with .Values.updateStrategy }}
  strategy:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jupiter-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jupiter-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.jupiter.solanaCredentials.enabled }}
          command: ["/bin/bash"]
          args: ["/tmp/startup.sh"]
          volumeMounts:
            - name: startup-script
              mountPath: /tmp/startup.sh
              subPath: startup.sh
          {{- end }}
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 25"]
          env:
            {{- if .Values.jupiter.solanaCredentials.enabled }}
            - name: X_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.jupiter.solanaCredentials.secretName }}
                  key: SOLANA_RPC_API_KEY
            - name: GEYSER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.jupiter.solanaCredentials.secretName }}
                  key: SOLANA_GRPC_ENDPOINT
            - name: SOLANA_RPC_ENDPOINT
              value: "https://edge.erpc.global?api-key=$(X_TOKEN)"
            {{- end }}
            {{- with .Values.env }}
            {{ include "jupiter-chart.renderEnv" . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.jupiter.solanaCredentials.enabled }}
          volumeMounts:
            - name: startup-script
              mountPath: /tmp/startup.sh
              subPath: startup.sh
          {{- else if .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
      {{- if .Values.jupiter.solanaCredentials.enabled }}
      volumes:
        - name: startup-script
          configMap:
            name: {{ include "jupiter-chart.fullname" . }}-startup-script
            defaultMode: 0755
      {{- else if .Values.volumes }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- else if .Values.configureDefaultAffinity }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - {{ .Release.Name }}
                topologyKey: kubernetes.io/hostname
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
